services:
  python_bot:
    container_name: python_bot
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - ./plugins/faiss:/app/plugins/faiss
    environment:
      - USER=${USER}
      - PASSWD=${PASSWD}
      - USER_API=${USER_API}
      - PASS_API=${PASS_API}
      - HEADLESS=${HEADLESS}
      - DISPLAY=:0
      - PYTHONUNBUFFERED=1
      
    privileged: true

    command: ["/bin/sh", "-c", "python main.py"]

    restart: unless-stopped